### ISSUE TITLE
Use rollup again

### ISSUE THREAD

**Issue by krisselden** [krisselden/fast-source-map#15]
This used to be easier to test and benchmark in d8.  Now that is no longer the case.  It was also intended to be able to be used in a browser.

**Comment by Turbo87** [comment]
> It was also intended to be able to be used in a browser.

sorry, I didn't know that. can you tell me more about your use case for using this in the browser? is it about being able to trace this via Chrome instead of Node? I think the main use case is still using this in Node via broccoli though, correct?

I guess what we could try is let TypeScript generate ES6 modules instead of CommonJS and then use Rollup to generate something that could be loaded in both browser and Node.
